### ISSUE TITLE
Hey! Issue with evekit.marketdata.MarketHistory.get_data_frame()

### ISSUE THREAD

**Issue by tykavanaugh** [OrbitalEnterprises/eve-market-strategies#2]
In both my attempts to use it and in simple running your notebooks I've found that even while I have an internet connection the kernel just freezes after "Retrieving (day)..." and I have to restart. The first day will always work, as I've tested it I've found that few days afterward, it will freeze.

I've attempted a few workaround (like iterating the date range) but I can't get it working. Any help?

**Comment by tykavanaugh** [comment]
Okay so I've found one odd workaround.  By making the date range n days longer than I actually want, and then telling the function dates = date_range[:-n] it works just fine.

**Comment by deadlybulb** [comment]
i'm setting up my environment to see if I can replicate.  What OS?

**Comment by tykavanaugh** [comment]
Oh wow that was fast!

Mac OSX 10.13.3.

I'm going to test this on a different internet connection when I get home, I'm suspecting the shoddy IT here might be part of the issue. But yeah the weird thing is that it only seems to hang when getting close to or at the last part of the date_range, it works almost every time if I date_range[:-n]

I have reproduced the issue in both your sample notebooks and in my own code, so it's gotta be unique to something on my end.

**Comment by deadlybulb** [comment]
Ok, I'm on Mac as well.  The following simple example works for me (and also reveals that I have some gaps in data which is bad)

```python
# Really simple example
#
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
from evekit.reference import Client
from evekit.online import Download
from evekit.marketdata import MarketHistory

# Tritanium in The Forge
type_id=34
region_id=10000002

# Get the last 30 days of data.  Note that there is usually a one day delay in the upload
# of the most recent data, so the actual range will likely exclude yesterday.  There is
# nothing magical about 30 days.  I just chose that value so this doesn't take very long to run.
import datetime
date_range = pd.date_range(datetime.date.today() - datetime.timedelta(days=30), datetime.date.today())

# This is the actual download call.  Adding verbose=True is usually helpful
market_history = MarketHistory.get_data_frame(dates=date_range, types=[type_id], regions=[region_id], 
                                              config=dict(local_storage=".", tree=True, skip_missing=True, 
                                                          verbose=True))

# Dump the data frame once it's loaded.
market_history
```

It should display the dates as they are loaded (with verbose=true).  If this doesn't work, then we can dig a little deeper depending on where it fails.

**Comment by tykavanaugh** [comment]
It was displaying the dates, it just just pause after the "loading (date) ....." right on the "....." once it was near the end of the list of dates. But I can't reproduce the problem on any network but the one I was on last night, so it probably some weird result of shitty government IT at work. Oddly that hacky fix of just end the date range a week or so in the future and doing date_range[:-days] works most of the time.

Thanks for looking into though! Really love that you put this together, it's a great way to practice algotrading and data science basics.

**Comment by deadlybulb** [comment]
happy to help.  feel free to re-open if you get stuck again.
